# Location & max sun angle for artificial light
max_sun_angle: 7 # degrees over the horizon at which time light can be turned off as it's light-enough anyway
latitude: 60.025369
longitude: 17.669363

fake_noon_hour: 11 # Treat as mid-day
hours_of_full_light: 10
minutes_of_sunrise: 120 # interval for dimming between 0 and 100% (both sunrise and sundown)

dimmer_controller: telldus
dimmer_step: 3

timezone: Europe/Stockholm
telldus:
  dimmer_id: 9611251
