# Location & max sun angle for artificial light
latitude: 60.025369
longitude: 17.669363

fake_noon_hour: 11 # Treat as mid-day
hours_of_full_light: 10
minutes_of_sunrise: 120 # interval for dimming between 0 and 100% (both sunrise and sundown)

dimmer_step: 2
dimmer_controller: telldus
dimmer_max: 50 # Start dimming downwards from here. Although 100 is 100.

telldus:
  dimmer_id: 9611251
